[package]
name = "jw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jw-internals = { version = "0.1.0", path = "../internals" }
rand = "0.8.5"
shellexpand = "2.1.2"
